### ISSUE TITLE
Notification services not available?

### ISSUE THREAD

**Issue by tedtms** [sentriz/betanin#68]
Hey, sorry if I'm being dense or missing something obvious, but the notification services menu doesn't give me any service type options in the dropdown next to "add new", the dropdown next to the URI for an added service doesn't appear, and to top it off, the service info help button doesn't do anything when I click it (you can see the little black bar under the menu selection next to "add" which is an unpopulated list):

![Screenshot_20220521_190128](https://user-images.githubusercontent.com/49801453/169715491-7d6d03bc-4e16-46b1-8002-ec743c7a4fd7.png)

When I run `betanin` as my beets user and just leave it in the console, then open the notifications settings page in betanin, I get this traceback:

```
Traceback (most recent call last):
  File "/home/beets/.local/lib/python3.8/site-packages/gevent/pywsgi.py", line 999, in handle_one_response
    self.run_application()
  File "/home/beets/.local/lib/python3.8/site-packages/gevent/pywsgi.py", line 945, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/home/beets/.local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/beets/.local/lib/python3.8/site-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/home/beets/.local/lib/python3.8/site-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/beets/.local/lib/python3.8/site-packages/werkzeug/middleware/proxy_fix.py", line 232, in __call__
    return self.app(environ, start_response)
  File "/home/beets/.local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/beets/.local/lib/python3.8/site-packages/flask_restplus/api.py", line 584, in error_router
    return original_handler(e)
  File "/home/beets/.local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/beets/.local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/beets/.local/lib/python3.8/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/beets/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/beets/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/beets/.local/lib/python3.8/site-packages/flask_restplus/api.py", line 584, in error_router
    return original_handler(e)
  File "/home/beets/.local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/beets/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/beets/.local/lib/python3.8/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/beets/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/beets/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/beets/.local/lib/python3.8/site-packages/flask_restplus/api.py", line 329, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/home/beets/.local/lib/python3.8/site-packages/flask_restplus/api.py", line 350, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/home/beets/.local/lib/python3.8/site-packages/flask_restplus/representations.py", line 25, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type LazyTranslation is not JSON serializable
2022-05-22T20:56:29Z {'REMOTE_ADDR': '192.168.100.100', 'REMOTE_PORT': '39558', 'HTTP_HOST': 'betanin.domain.com', (hidden keys: 34)} failed with TypeError
```

Remember, to get betanin to install I had to substitute `importlib-metadata>=4.4` instead of the `importlib-metadata==3.3.0` listed in `betanin`'s requirements. The `markdown` dependency doesn't work properly otherwise since it requires `importlib-metadata` 4.4 or above. Once I install it, `betanin` launches fine but now I'm getting this problem.

**Comment by sentriz** [comment]
oh shit, it's the same for me. i'll have a look

**Comment by sentriz** [comment]
should be fixed now

**Comment by sentriz** [comment]
@tedtms looks like the CI didn't manage to push it. just tried again, it should be there as 0.3.38 now

**Comment by tedtms** [comment]
Hey, that did it. Notification options are showing up properly now. Thanks!
